apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: myweb
    app.kubernetes.io/instance: myargocdapp1
  name: myweb-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: myweb
  type: NodePort
status:
  loadBalancer: {}
